"""added_constraint_unique_user_id_vacancy_id

Revision ID: 56b57b0fcd82
Revises: 068b623cbca7
Create Date: 2026-06-13 13:52:31.613303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b57b0fcd82'
down_revision: Union[str, Sequence[str], None] = '068b623cbca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_user_vacancy', 'application', ['user_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_user_vacancy', 'application', type_='unique')
    # ### end Alembic commands ###
