"""changed for cascad delete and added id in many to many

Revision ID: 6e969ac19376
Revises: cb7e70961a18
Create Date: 2026-06-07 16:04:24.492520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e969ac19376'
down_revision: Union[str, Sequence[str], None] = 'cb7e70961a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # Получаем список существующих колонок в базе данных
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    # 1. Проверяем таблицу user_skills
    user_skills_cols = [c['name'] for c in inspector.get_columns('user_skills')]
    if 'id' not in user_skills_cols:
        op.add_column('user_skills', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    
    # Уникальное ограничение (добавляем через batch_alter_table, так как это SQLite)
    with op.batch_alter_table('user_skills') as batch_op:
        # Проверяем, нет ли уже такого ограничения, чтобы не вызвать новую ошибку
        existing_constraints = inspector.get_unique_constraints('user_skills')
        if not any(c['name'] == 'uq_user_skill' for c in existing_constraints):
            batch_op.create_unique_constraint('uq_user_skill', ['user_id', 'skill_id'])

    # 2. Проверяем таблицу vacancy_skills
    vacancy_skills_cols = [c['name'] for c in inspector.get_columns('vacancy_skills')]
    if 'id' not in vacancy_skills_cols:
        op.add_column('vacancy_skills', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        
    with op.batch_alter_table('vacancy_skills') as batch_op:
        existing_vacancy_constraints = inspector.get_unique_constraints('vacancy_skills')
        if not any(c['name'] == 'uq_vacancy_skill' for c in existing_vacancy_constraints):
            batch_op.create_unique_constraint('uq_vacancy_skill', ['vacancy_id', 'skill_id'])



# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('user_skills', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
#     op.create_unique_constraint('uq_user_skill', 'user_skills', ['user_id', 'skill_id'])
#     op.add_column('vacancy_skills', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
#     op.create_unique_constraint('uq_vacancy_skill', 'vacancy_skills', ['vacancy_id', 'skill_id'])
#     # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_vacancy_skill', 'vacancy_skills', type_='unique')
    op.drop_column('vacancy_skills', 'id')
    op.drop_constraint('uq_user_skill', 'user_skills', type_='unique')
    op.drop_column('user_skills', 'id')
    # ### end Alembic commands ###
