"""remove_composite_pk_from_application

Revision ID: cb7e70961a18
Revises: cfba3030a44d
Create Date: 2026-06-03 22:18:53.746731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7e70961a18'
down_revision: Union[str, Sequence[str], None] = 'cfba3030a44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Для SQLite

def upgrade() -> None:
    with op.batch_alter_table('application', schema=None, recreate='always') as batch_op:
        # Устанавливаем первичный ключ только на поле id, которое наследуется из базового класса
        batch_op.create_primary_key('pk_application', ['id'])

def downgrade() -> None:
    with op.batch_alter_table('application', schema=None, recreate='always') as batch_op:
        batch_op.create_primary_key('pk_application', ['user_id', 'vacancy_id'])


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     pass
#     # ### end Alembic commands ###
