"""add_unique_to_vacancy_url

Revision ID: cfba3030a44d
Revises: 230ccd353dd8
Create Date: 2026-06-03 20:44:30.857619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfba3030a44d'
down_revision: Union[str, Sequence[str], None] = '230ccd353dd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Для SQlite

def upgrade() -> None:
    # Используем batch-режим, передавая имя ограничения 'uq_vacancy_url' вместо None
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_vacancy_url', ['url'])


def downgrade() -> None:
    with op.batch_alter_table('vacancy', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vacancy_url', type_='unique')


# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_unique_constraint(None, 'vacancy', ['url'])
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(None, 'vacancy', type_='unique')
#     # ### end Alembic commands ###
